export type BioWoundLocale = 'en' | 'ms';

export const clinic = {
  whatsappNumber: '60178974751',
  primaryPhone: '+60397714550',
  mobilePhone: '+60178974751',
  primaryPhoneLabel: '+60 3-9771 4550',
  mobilePhoneLabel: '+60 17-897 4751',
  address: 'G06 & G07, VUE Residence Service Suite 102, Jalan Pahang, 53300 Kuala Lumpur',
  mapsUrl:
    'https://www.google.com/maps/search/?api=1&query=G06%20%26%20G07%20VUE%20Residence%20Service%20Suite%20102%20Jalan%20Pahang%2053300%20Kuala%20Lumpur',
  mainWebsite: 'https://klinikinocare.com/',
  woundCareSource: 'https://www.moh.gov.my/moh/resources/Penerbitan/Garis%20Panduan/Garis%20Panduan%20Umum%28KKM%29/Wound_Care_Manual.pdf',
} as const;

export const bioWoundContent = {
  en: {
    languageLabel: 'BM',
    languageAria: 'Tukar ke Bahasa Melayu',
    skip: 'Skip to main content',
    navAria: 'BioWound navigation',
    navOpen: 'Open menu',
    navClose: 'Close menu',
    nav: [
      ['Who we help', '#who-we-help'],
      ['Your care', '#care-pathway'],
      ['FAQs', '#faqs'],
      ['Visit us', '#visit'],
    ],
    cta: 'Ask for an assessment',
    call: 'Call clinic',
    hero: {
      eyebrow: 'BioWound · Wound care by Klinik Inocare',
      title: 'A wound that lingers deserves a closer look.',
      body: 'Structured wound assessment, an individual care plan and clear follow-up—at our Kuala Lumpur clinic or, where suitable and available, at home.',
      note: 'Suitability and treatment depend on clinical assessment.',
      location: 'Opposite HKL main entrance',
      promise: 'Trusted Care. Inspired Innovation.',
    },
    reassurance: [
      ['Assessment first', 'We look at the wound and the health factors that can affect it.'],
      ['A plan you understand', 'Your clinician explains the proposed care and what happens next.'],
      ['Follow-up that adapts', 'Progress is reviewed and the plan may change with your needs.'],
    ],
    who: {
      eyebrow: 'Who we help',
      title: 'When a wound needs structured care',
      intro: 'Speak with our team if you have a wound that is slow to improve, keeps returning or needs professional dressing and monitoring.',
      items: [
        ['Diabetic foot wounds', 'Foot wounds in people living with diabetes need timely assessment and attention to pressure and overall health.'],
        ['Pressure wounds', 'Wounds linked to prolonged pressure may need pressure relief, skin protection and an individual plan.'],
        ['Leg ulcers', 'A clinician can assess the wound and whether circulation or other health factors may need further attention.'],
        ['Post-operative wounds', 'For wounds that need dressing support, review or monitoring after a procedure.'],
        ['Hard-to-heal wounds', 'For a wound that has stalled, changed or has not progressed as expected.'],
        ['Caregiver support', 'Clear guidance for family members or carers supporting day-to-day wound care.'],
      ],
      safety: 'If you are very unwell, bleeding heavily or believe this is an emergency, call 999 or go to the nearest Emergency Department. WhatsApp is not an emergency service.',
    },
    assessment: {
      eyebrow: 'Assessment-led care',
      title: 'We start by understanding the whole picture',
      body: 'A wound is more than its surface. Your clinician may consider the wound tissue, signs of inflammation or infection, moisture, wound edges, pressure, circulation and relevant health history before discussing a plan.',
      cards: [
        ['01', 'Wound assessment', 'Review of the wound, surrounding skin, symptoms and how it has changed.'],
        ['02', 'Health context', 'Relevant conditions, medication, mobility, nutrition and other factors are discussed.'],
        ['03', 'Care options', 'Options may include appropriate dressings, debridement, pressure offloading or referral when indicated.'],
        ['04', 'Review plan', 'Follow-up is planned according to clinical findings and your care needs.'],
      ],
      qualifier: 'Not every option is suitable for every wound. Recommendations are made only after assessment.',
    },
    pathway: {
      eyebrow: 'Your care pathway',
      title: 'Clear steps. No guesswork.',
      intro: 'You do not need to choose a dressing or treatment before contacting us.',
      steps: [
        ['Message the team', 'Tell us who the care is for and whether you are asking about a clinic appointment or home visit. Avoid sending unnecessary sensitive information in your first message.'],
        ['Attend an assessment', 'Bring a medication list, relevant reports and any dressing or care information you already have.'],
        ['Discuss the care plan', 'Your clinician explains the findings, suitable options, expected follow-up and charges before care is agreed.'],
        ['Review progress', 'The wound and overall plan are reviewed over time, with changes made when clinically appropriate.'],
      ],
      servicesTitle: 'Care options considered after assessment',
      services: ['Advanced wound dressings', 'Debridement when indicated', 'Pressure offloading', 'Clinic-based follow-up', 'Home wound care where available', 'Referral when further care is needed'],
    },
    homeCare: {
      eyebrow: 'Clinic or home care',
      title: 'Care that considers mobility and comfort',
      body: 'Clinic appointments are available in Kuala Lumpur. Home visits may be considered for suitable patients and locations; availability must be confirmed with the clinic team.',
      points: ['Ask about coverage for your area', 'Share any access or mobility needs', 'Confirm appointment timing and current charges'],
      button: 'Ask about home wound care',
    },
    faq: {
      eyebrow: 'Frequently asked questions',
      title: 'Useful to know before you contact us',
      items: [
        ['How soon should I arrange an assessment?', 'If a wound is not improving, has changed, or you are concerned about it, contact a healthcare professional for advice. Urgent or emergency symptoms should not be sent through WhatsApp.'],
        ['How many visits will I need?', 'This varies with the wound, your health and how the wound responds. The clinician can discuss an initial follow-up plan after assessment.'],
        ['Do you offer home visits?', 'Home wound care may be available depending on your location, clinical situation and the team’s schedule. Please confirm with the clinic.'],
        ['What will it cost?', 'Charges depend on the assessment and agreed care plan. Ask the team for current charges before confirming an appointment or service.'],
        ['What should I bring?', 'Bring your medication list, relevant medical reports, discharge or dressing instructions, and a list of questions you would like answered.'],
        ['Can this page diagnose my wound?', 'No. This page provides general information and does not replace an examination, diagnosis or emergency care.'],
      ],
    },
    visit: {
      eyebrow: 'Visit Klinik Inocare',
      title: 'Begin with a conversation',
      body: 'Message or call our team to ask about a wound assessment. Please confirm current opening hours before travelling.',
      addressLabel: 'Clinic address',
      landmark: 'Opposite HKL main entrance',
      directions: 'Open directions',
      phoneLabel: 'Contact',
      hoursLabel: 'Before your visit',
      hours: 'Please confirm the current opening hours and appointment availability with the clinic team.',
    },
    footer: {
      summary: 'Assessment-led wound care in Kuala Lumpur, with home-care options subject to suitability and availability.',
      mainSite: 'Main clinic website',
      source: 'Patient information reference: Ministry of Health Malaysia Wound Care Manual',
      medical: 'Medical information on this page is general and does not replace clinical assessment, diagnosis or emergency care.',
      rights: 'Klinik Inocare. All rights reserved.',
    },
  },
  ms: {
    languageLabel: 'EN',
    languageAria: 'Switch to English',
    skip: 'Langkau ke kandungan utama',
    navAria: 'Navigasi BioWound',
    navOpen: 'Buka menu',
    navClose: 'Tutup menu',
    nav: [
      ['Siapa yang kami bantu', '#who-we-help'],
      ['Penjagaan anda', '#care-pathway'],
      ['Soalan lazim', '#faqs'],
      ['Kunjungi kami', '#visit'],
    ],
    cta: 'Tanya tentang penilaian',
    call: 'Hubungi klinik',
    hero: {
      eyebrow: 'BioWound · Penjagaan luka oleh Klinik Inocare',
      title: 'Luka lambat sembuh perlu dinilai dengan teliti.',
      body: 'Penilaian luka yang teratur, pelan penjagaan individu dan susulan yang jelas—di klinik kami di Kuala Lumpur atau, jika sesuai dan tersedia, di rumah.',
      note: 'Kesesuaian dan rawatan bergantung pada penilaian klinikal.',
      location: 'Bertentangan pintu masuk utama HKL',
      promise: 'Trusted Care. Inspired Innovation.',
    },
    reassurance: [
      ['Penilaian dahulu', 'Kami menilai luka serta faktor kesihatan yang boleh mempengaruhinya.'],
      ['Pelan yang anda fahami', 'Doktor menerangkan penjagaan yang dicadangkan dan langkah seterusnya.'],
      ['Susulan yang disesuaikan', 'Kemajuan dinilai dan pelan boleh diubah mengikut keperluan anda.'],
    ],
    who: {
      eyebrow: 'Siapa yang kami bantu',
      title: 'Apabila luka memerlukan penjagaan teratur',
      intro: 'Hubungi pasukan kami jika luka lambat pulih, berulang atau memerlukan balutan dan pemantauan profesional.',
      items: [
        ['Luka kaki diabetes', 'Luka kaki bagi penghidap diabetes perlu dinilai awal dengan perhatian kepada tekanan dan kesihatan keseluruhan.'],
        ['Luka tekanan', 'Luka akibat tekanan berpanjangan mungkin memerlukan pengurangan tekanan, perlindungan kulit dan pelan individu.'],
        ['Ulser kaki', 'Doktor boleh menilai luka serta sama ada peredaran darah atau faktor kesihatan lain memerlukan perhatian lanjut.'],
        ['Luka selepas pembedahan', 'Untuk luka yang memerlukan bantuan balutan, penilaian atau pemantauan selepas prosedur.'],
        ['Luka sukar sembuh', 'Untuk luka yang terhenti proses penyembuhan, berubah atau tidak pulih seperti yang dijangka.'],
        ['Sokongan penjaga', 'Panduan jelas untuk ahli keluarga atau penjaga yang membantu penjagaan luka harian.'],
      ],
      safety: 'Jika anda sangat tidak sihat, mengalami pendarahan banyak atau menganggapnya kecemasan, hubungi 999 atau pergi ke Jabatan Kecemasan terdekat. WhatsApp bukan perkhidmatan kecemasan.',
    },
    assessment: {
      eyebrow: 'Penjagaan berasaskan penilaian',
      title: 'Kami bermula dengan memahami keadaan menyeluruh',
      body: 'Luka bukan sekadar permukaan kulit. Sebelum membincangkan pelan, doktor mungkin menilai tisu luka, tanda keradangan atau jangkitan, kelembapan, tepi luka, tekanan, peredaran darah dan sejarah kesihatan berkaitan.',
      cards: [
        ['01', 'Penilaian luka', 'Pemeriksaan luka, kulit sekeliling, gejala dan perubahan yang berlaku.'],
        ['02', 'Konteks kesihatan', 'Keadaan berkaitan, ubat, pergerakan, pemakanan dan faktor lain dibincangkan.'],
        ['03', 'Pilihan penjagaan', 'Pilihan mungkin termasuk balutan sesuai, debridemen, pengurangan tekanan atau rujukan jika diperlukan.'],
        ['04', 'Pelan susulan', 'Susulan dirancang mengikut dapatan klinikal dan keperluan penjagaan anda.'],
      ],
      qualifier: 'Bukan semua pilihan sesuai untuk setiap luka. Cadangan hanya dibuat selepas penilaian.',
    },
    pathway: {
      eyebrow: 'Laluan penjagaan anda',
      title: 'Langkah jelas. Tanpa teka-teki.',
      intro: 'Anda tidak perlu memilih balutan atau rawatan sebelum menghubungi kami.',
      steps: [
        ['Hubungi pasukan kami', 'Beritahu penjagaan ini untuk siapa dan sama ada anda bertanya tentang janji temu klinik atau lawatan ke rumah. Elakkan menghantar maklumat sensitif yang tidak diperlukan dalam mesej pertama.'],
        ['Hadir untuk penilaian', 'Bawa senarai ubat, laporan berkaitan dan maklumat balutan atau penjagaan yang sedia ada.'],
        ['Bincangkan pelan penjagaan', 'Doktor menerangkan dapatan, pilihan yang sesuai, jangkaan susulan dan caj sebelum penjagaan dipersetujui.'],
        ['Nilai kemajuan', 'Luka dan pelan keseluruhan dinilai dari semasa ke semasa, dengan perubahan dibuat apabila sesuai secara klinikal.'],
      ],
      servicesTitle: 'Pilihan penjagaan yang dipertimbangkan selepas penilaian',
      services: ['Balutan luka lanjutan', 'Debridemen jika diperlukan', 'Pengurangan tekanan', 'Susulan di klinik', 'Penjagaan luka di rumah jika tersedia', 'Rujukan jika penjagaan lanjut diperlukan'],
    },
    homeCare: {
      eyebrow: 'Penjagaan di klinik atau rumah',
      title: 'Penjagaan yang mengambil kira pergerakan dan keselesaan',
      body: 'Janji temu klinik tersedia di Kuala Lumpur. Lawatan ke rumah boleh dipertimbangkan untuk pesakit dan lokasi yang sesuai; ketersediaan perlu disahkan dengan pasukan klinik.',
      points: ['Tanya tentang liputan kawasan anda', 'Maklumkan keperluan akses atau pergerakan', 'Sahkan waktu janji temu dan caj semasa'],
      button: 'Tanya tentang penjagaan luka di rumah',
    },
    faq: {
      eyebrow: 'Soalan lazim',
      title: 'Perkara berguna sebelum menghubungi kami',
      items: [
        ['Bilakah saya perlu mengatur penilaian?', 'Jika luka tidak bertambah baik, telah berubah atau menimbulkan kebimbangan, hubungi profesional kesihatan untuk nasihat. Gejala segera atau kecemasan tidak patut dihantar melalui WhatsApp.'],
        ['Berapa kali lawatan diperlukan?', 'Ini berbeza mengikut luka, kesihatan anda dan tindak balas luka. Doktor boleh membincangkan pelan susulan awal selepas penilaian.'],
        ['Adakah lawatan ke rumah tersedia?', 'Penjagaan luka di rumah mungkin tersedia bergantung pada lokasi, keadaan klinikal dan jadual pasukan. Sila sahkan dengan klinik.'],
        ['Berapakah kosnya?', 'Caj bergantung pada penilaian dan pelan penjagaan yang dipersetujui. Tanya pasukan tentang caj semasa sebelum mengesahkan janji temu atau perkhidmatan.'],
        ['Apakah yang perlu saya bawa?', 'Bawa senarai ubat, laporan perubatan berkaitan, arahan discaj atau balutan dan senarai soalan yang ingin ditanya.'],
        ['Bolehkah halaman ini mendiagnosis luka saya?', 'Tidak. Halaman ini menyediakan maklumat umum dan tidak menggantikan pemeriksaan, diagnosis atau rawatan kecemasan.'],
      ],
    },
    visit: {
      eyebrow: 'Kunjungi Klinik Inocare',
      title: 'Mulakan dengan perbualan',
      body: 'WhatsApp atau hubungi pasukan kami untuk bertanya tentang penilaian luka. Sila sahkan waktu operasi semasa sebelum datang.',
      addressLabel: 'Alamat klinik',
      landmark: 'Bertentangan pintu masuk utama HKL',
      directions: 'Buka pandu arah',
      phoneLabel: 'Hubungi',
      hoursLabel: 'Sebelum kunjungan',
      hours: 'Sila sahkan waktu operasi semasa dan ketersediaan janji temu dengan pasukan klinik.',
    },
    footer: {
      summary: 'Penjagaan luka berasaskan penilaian di Kuala Lumpur, dengan pilihan penjagaan di rumah tertakluk pada kesesuaian dan ketersediaan.',
      mainSite: 'Laman utama klinik',
      source: 'Rujukan maklumat pesakit: Manual Penjagaan Luka Kementerian Kesihatan Malaysia',
      medical: 'Maklumat perubatan di halaman ini adalah umum dan tidak menggantikan penilaian klinikal, diagnosis atau rawatan kecemasan.',
      rights: 'Klinik Inocare. Hak cipta terpelihara.',
    },
  },
} as const;

export type BioWoundContent = (typeof bioWoundContent)[BioWoundLocale];
